services:
  postgres:
    image: postgres:16
    container_name: chat_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpass
      POSTGRES_DB: chatdb
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: chat_redis
    restart: unless-stopped
    ports:
      - 6380:6379
    volumes:
      - redisdata:/data
    command: [
      "redis-server",
      "--appendonly",
      "yes"
    ]

  chat-app:
    build: .
    container_name: chat_app
    restart: unless-stopped
    env_file: .env
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:3000"      # maps container port 3000 to host port 5000
    volumes:
      - ./logs:/app/logs

volumes:
  pgdata:
  redisdata: