services:
  postgres:
    image: postgres:16
    container_name: chat_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpass
      POSTGRES_DB: chatdb
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: chat_redis
    restart: unless-stopped
    ports:
      - 6380:6379
    volumes:
      - redisdata:/data
    command: [
      "redis-server",
      "--appendonly",
      "yes"
    ]


volumes:
  pgdata:
  redisdata: